# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Stock' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stock
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftSpinner'

  target 'StockTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StockUITests' do
    # Pods for testing
  end

end
